config/routes.rb
ManthanErp::Application.routes.draw do

  resources :messages

  get 'locations/index'

  resources :grade_lab_mappings do
    collection do
      get "get_grades_subjects_service_view"
      get "all_subjects"
      get "get_subjects_grades_service_view"
      post "save_subjects_mappings"
      get "get_grades_subjects_service_view"    
    end
  end

  resources :guest_managements do
    collection do
      get "get_role_view"
    end
  end
 

  resources :food_wastages do
    collection do
      get "get_food_wastage"
    end
  end
  

  get "teaching_plans/new"
  get "teaching_plans/edit"
  get "teaching_plans/index"
  get "teaching_plans/show"
  resources :lib_reports do
    collection do
      get 'Leastused'
      get 'popup'
      end
    end
  resources :donation_of_books do
    collection do
      get 'gradeserviceview'
      get 'sectionserviceview'
      end
    end
  
  resources :student_route_mappings do
    collection do
      get 'get_route_optimization'
      get "get_search_students"
      get "get_up_route_view"
      get "get_down_route_view"
      get "get_student_view"
      post "save_route"
    end
  end
  
  resources :interviewschedulrs do
    member do
      get 'home_index'
    end
  end
  resources :block_books do
    collection do
      get 'get_book_service_view'
      get 'getbooks'
      post 'savebooks'
      post 'damagebooks'
      
    end
  end 
 
  resources :request_new_books do
    collection do
      get 'request_new'
      get 'request_approval'
      post 'create_bulk'
      get 'request_new_book'
      get 'request_accept'
      get 'suggest_teacher'
      get 'book_accept'
      get 'book_reject'
     
    end
     member do
      get 'home_request_approval'
      get 'book_request_approval'
      get 'bookrequest'
  end
  end
  resources :issuings do
    collection do
      get "student_book_issuings"
      get 'gradeserviceview'
      get 'grade_section_service'
    end
  end
  resources :damagebooks do
    collection do
      get 'get_book_service_view'
      post 'damagebooks'
      get 'get_damage_books'
    end
  end 
  resources :staffs
  get "staffs/staffview"

  devise_for :users, :controllers => { :sessions => 'sessions'}
  
  get 'auto_search/autocomplete_location_master_location_name'
  get 'auto_search/autocomplete_student_master_name'
  get 'auto_search/autocomplete_faculty_master_faculty_name'
  get 'auto_search/student_name_by_grade_and_section'
  get 'auto_search/autocomplete_book_isbn'
  get 'auto_search/autocomplete_staff_grade'
  get 'auto_search/autocomplete_user_email'
  get 'auto_search/autocomplete_mail_search'
  get "time_tables/gradeserviceview"
  get "time_tables/sectionserviceview"
  get "/time_tables/subjectserviceview"
  post "/time_tables/saveperiods"
  get "/time_tables/timetableserviceview"
  post "/time_tables/getperiods"
  get "/time_tables/getperiods"
  get "/time_tables/defaultperiodsserviceview"
  post "/time_tables/checktimetable"
  get "/time_tables/checktimetable"

  #get "/teaching_plans/gradeserviceview"
  #get "/teaching_plans/sectionserviceview"

  resources :time_tables do
    collection do       
      get "get_sections_for_grade"
      get "get_subjects_for_grade"
    end 
  end 

  resources :books do 
    member do 
    end
    collection do       
      post 'create_bulk'
      post 'add_bulk'
    end
  end
  resources :teaching_plans do
     collection do
      get "calendardata"
      get "getfacultyidservice"
      get "getgradessectionsservice"      
      get 'calendarpopup'
      get 'monthlywiseplan'
      get 'get_grade_section_subject_service'
      get 'teaching_date'
      get 'getmonthlycalendarservice'
      get 'getmonthdataservice'
      get "student_teaching_plans"
      get 'getfacultydatesservice' 
      get 'plan_exists' 

    end
  end

  resources :documentuploaders do
    member do
      get 'home_index'
    end
  end
  
  resources :new_vehicles do
    collection do
      get 'home'
      get 'get_vendor_name'
    end
  end
  resources :forms do
    member do
      get 'home_index'
    end
  end

  resources :discounts 
  resources :approval_items do
    member do
      put "approve"
      put "reject"
    end
    collection do
      get "fee_structure_approval_item"
    end
  end
  resources :events

  resources :fee_types do
    collection do
      post "create_bulk"
    end
  end
  resources :fee_grade_buckets do
    collection do
      post "create_bulk"
      get "all_grades"
      delete "destroy_all"
    end
  end
  resources :term_definitions do
    collection do
      post "create_bulk"
      delete "destroy_all"
    end
  end
  
  resources :grade_wise_fees do
    collection do
      get "grade_wise_fee_view"
      post "save_grade_wise_fee_grid"
      get "grade_wise_fee_of_student"
    end
  end


  resources :term_wise_grade_fees do
    collection do
      get "term_wise_grade_fee"
      post "save_term_wise_fee_grid"
      get "term_wise_fee_of_student"
    end
  end

  
  resources :monthly_pdc_amounts  do
    collection do
      get "monthly_pdc_amounts"
      post "save_monthly_pdc_amounts"
      get "month_wise_fee_of_student"
    end
  end


  resources :post_dated_cheques do
    collection do
      post "create_bulk"
      delete "destroy_all"
    end
  end
  
  get "fee_alerts/fee_struct_mail_to_parents" 

  resources :student_masters do
    collection do
      get "belongs_to_parent"
      get "new_upload"
      post "upload"
    end
    member do
      get 'monthly_pdcs'
      get 'next_term_fee'
      get "annual_discount_details"
      get "dashboard"
      put "update_address"
      get "attendance_calendar_for_month"
      get "student_summarized_monthly_report"
      get "transport_details"
      put "change_transport"
    end
  end
  
  resources :parent_payment_masters do
    collection do
      get "pay"
      get "transaction_types"
      get "student_transactions"
    end
    member do
      get "pending_pdcs"
      get "cleared_pdcs"
      get "payment_transactions"
      get "submitted_pdcs"
      get "print"
    end
  end
  resources :parent_payment_transactions do
    member do
      get "print"
      get "in_detail"
    end
  end
  

 
  
  resources :staffs do
    member do
      get 'event_new'
    end
    collection do
      get 'event_index'
      get 'staffs/staffview'
    end
  end

  resources :parent_cheques

  resources :job_runs do
    member do
      get "failure_recipients"
    end
  end
  
  resources :default_masters do 
    collection do
      get "day_ends"
      put "days"
    end
  end
  
  resources :academics do
    collection do
      get "get_grades"
      get "get_academics_subjects"
      get "get_sections_for_grade"
      get "get_academics_subjects_for_grade"
    end
  end


  resources :teachers_time_tables do
    collection do
      get "get_faculty_names_view"
      get "get_faculty_garde_sections_view"
      get "check_teachers_timetable"
      post "saveperiods"
      post "getperiods"
    end  
  end

  resources :teacher_grade_mappings do
    collection do
      get "check_teachers_grades_mapping"
      post "savemappings"
      post "getmappings" 
      post "deletemappings"  
      get "show_grade_wise"
      get "get_grade_wise_mappings"   
      end
  end
  
  get "/parent_payment_transactions/parent_transactions"
  get "/parent_payment_transactions/admin_transactions"

  resources :grade_masters do
    member do
      get "sections"
    end
    resources :section_masters
  end

  resources :parent_masters do
    collection do
      get "new_upload"
      post "upload"
    end
  end

  resources :class_teacher_mappings do
    collection do
      get "get_grade_wise_mappings"
      get "get_grade_wise_faculty_names"  
      get "get_class_teacher_mappings" 
      post "save_mappings"
      post "deletemappings"
      get "check_for_teacher_mapping"
    end  
  end

  resources :grades_sections_mappings do
    collection do
      get "get_grades_sections_service_view"
      post "save_sections_mappings" 
      post "save_grades_mappings"         
    end  
  end

  resources :grades_subjects_mappings do
    collection do
      get "get_grades_subjects_service_view"
      post "save_subjects_mappings" 
      post "save_grades_mappings"    
    end  
  end 

  resources :gradings do
    collection do
    get "get_grading_service_view"
    post "save_gradings_mappings"
    post "delete_grading_mappings"
    end
  end
  
  resources :location_masters

  
  resources :recruitments do
    member do
      
      put 'update_admission'
      get "homeindex"
      get "view_document"
      get 'create_enquiry'
      get "document_verification"
      get 'view_assessment'
      get 'assessment_result'
      put 'update_rec'
      put 'update_ass'
      put 'update_man'
      put 'update_close'
      get 'assessment_new'
    end
    collection do
      
      get 'recruitment_home'
      get 'get_subject_view'
      get 'get_klass_view'
      get 'enquiry_new'
      post 'create_enquiry'
      get 'document_index'
      get 'sports_index'
      get 'assessment_index'
      get 'assessment_completed_index'
      get 'management_index'
      get 'selected_staffs'
      get 'closed_forms'
    end
  end
  resources :staff_admissions do
    member do
      get 'homeindex'
      get "document_verification"
      post 'update_close'
      put 'update_admission'
      put 'update_man'
    end
    collection do
      get 'get_head_view'
      get 'get_post_view'
      get 'get_subject_view'
      get 'get_klass_view'
      get 'enquiry_index'
     
    end
  end
  
  resources :teacher_leaders
  
  resources :adds do 
    collection do
      get 'get_dept_view'
    end
  end
 
  resources :assessment_criterias do
    collection do
      get "get_assessment_criteria_service"       
      post "save_assessment_criterias"
      post "deletemappings"
      get "get_grade_subject_service"
      get "get_assessment_criteria"
    end
  end

app/models/staff.rb
class Staff < ActiveRecord::Base
  
  scope :search, lambda { |id| where(:id => id)}
  def self.search(search)
    if search
     find(:all,:conditions => ['grade LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.search(params[:search])
   
  end
  def event_new
    @event = Event.new
  end
  def staffview
    respond_to do |format|
      format.json do
        staffs = Staff.all.map do |staff|
          {staff: staff.staff_name, id: staff.id}
        end
        render :json => staffs
      end
    end
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    
    @staff = Staff.new(staff_params)
    respond_to do |format|
      if @staff.save
        format.html { redirect_to staffs_path, notice: 'Staff was successfully created.' }
       
      else
        format.html { render action: 'new' }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to staffs_path, notice: 'Staff was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:staff_name, :staff_exp, :grade, :start_time, :end_time, :period, :date)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_event.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg
  .row
    .field
      .col-sm-3
        = f.label :title, :class => 'control-label'
      .col-sm-3
        = f.text_field :title, :class => 'form-control'
  %br
  .row   
    .field
      .col-sm-3
        = f.label :description, :class => 'control-label'
      .col-sm-3
        = f.text_area :description, :class => 'form-control'
  %br
  .row
    .field
      .col-sm-3
        = f.label :staff, :class => 'control-label'
      .col-sm-3
        = f.text_field :staff, :class => 'form-control'
  %br
  .row
    .field
      .col-sm-3
        = f.label :grade, :class => 'control-label'
      .col-sm-3
        = f.text_field :grade, :class => 'form-control'
  %br
  .row
    .field
      .col-sm-3
        = f.label :start_time, :class => 'control-label'
      .col-sm-3
        = f.datetime_select :start_time, :class => 'form-control'
  %br
  .row
    .field
      .col-sm-3
        = f.label :end_time, :class => 'control-label'
      .col-sm-3
        = f.datetime_select :end_time, :class => 'form-control'
  %br
  .col-sm-3
    .pull-right
      = f.submit 'Save',:class => 'btn btn-primary'
      

app/views/staffs/_form.html.haml
= form_for @staff do |f|
  - if @staff.errors.any?
    #error_explanation
      %h2= "#{pluralize(@staff.errors.count, "error")} prohibited this staff from being saved:"
      %ul
        - @staff.errors.full_messages.each do |msg|
          %li= msg
 
  %table
    .row
      .field
        %tr
          .col-sm-3
            = f.label :staff_name,:class => 'control-label'
        %tr
          .col-sm-3
            = f.text_field :staff_name, :class => 'form-control'
    .row
      .field
        %tr
          .col-sm-3
            = f.label :staff_exp
        %tr
          .col-sm-3
            = f.text_field :staff_exp, :class => 'form-control'
    .row
      .field
        %tr
          .col-sm-3
            = f.label :grade
        %tr
          .col-sm-3
            = f.select :grade,options_for_select([['PP1'],['PP2'],['Grade-1'],['Grade-2'],['Grade-3'],['Grade-4'],['Grade-5'],['Grade-6'],['Grade-7'],['Grade-8'],['Grade-9'],['Grade-10'],['Grade-11'],['Grade-12']]), {:class => 'col-sm-4 form-control'}
    .row
      .field
        %tr
          .col-sm-3
            = f.label :start_time
        %tr
          .col-sm-3
            = f.text_field :start_time, :class => 'timepicker form-control'
    .row
      .field
        %tr
          .col-sm-3
            = f.label :end_time
        %tr
          .col-sm-3
            = f.text_field :end_time, :class => 'timepicker form-control'
    .row
      .field
        %tr
          .col-sm-3
            = f.label :period
        %tr
          .col-sm-3
            = f.text_field :period, :class => 'form-control'
    .row
      .field
        %tr
          .col-sm-3
            = f.label :date
        %tr
          .col-sm-3
            = f.text_field :date, :class => 'datepicker form-control'
    %br
    .col-sm-2
      .pull-right
        = f.submit 'Save',:class => 'btn btn-primary'

app/views/staffs/edit.html.haml
%h1 Editing Assessment
%center
  = render 'form'
.col-sm-3
  .pull-left
    = link_to button_tag('Back',:class => 'btn btn-primary'), staffs_path
  %br

app/views/staffs/event_new.html.haml
%h4 NEW EVENT
= render 'event'
.col-sm-3
  .pull-left
    = link_to button_tag('Back',:class=> 'btn btn-primary'), events_path

app/views/staffs/index.html.haml
.pull-right
  %button.btn.btn-primary{"data-target" => "#myModal","data-toggle" => "modal"}= "New Event"
  #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
          %h4#myModalLabel.modal-title New Assessment
        = form_for Staff.new do |f|
          .modal-body
            %table
              .row
                .field
                  %tr
                    .col-sm-3
                      = f.label :staff_name,:class => 'control-label'
                  %tr
                    .col-sm-3
                      = f.text_field :staff_name, :class => 'form-control'
              .row
                .field
                  %tr
                    .col-sm-3
                      = f.label :staff_exp
                  %tr
                    .col-sm-3
                      = f.text_field :staff_exp, :class => 'form-control'
              .row
                .field
                  %tr
                    .col-sm-3
                      = f.label :grade
                  %tr
                    .col-sm-3
                      = f.select :grade,options_for_select([['PP1'],['PP2'],['Grade-1'],['Grade-2'],['Grade-3'],['Grade-4'],['Grade-5'],['Grade-6'],['Grade-7'],['Grade-8'],['Grade-9'],['Grade-10'],['Grade-11'],['Grade-12']]), {:class => 'col-sm-4 form-control'}
              .row
                .field
                  %tr
                    .col-sm-3
                      = f.label :start_time
                  %tr
                    .col-sm-3
                      = f.time_field :start_time, :class => 'form-control'
              .row
                .field
                  %tr
                    .col-sm-3
                      = f.label :end_time
                  %tr
                    .col-sm-3
                      = f.time_field :end_time, :class => 'form-control'
              .row
                .field
                  %tr
                    .col-sm-3
                      = f.label :period, :class => 'control-label'
                  %tr
                    .col-sm-3
                      = f.text_field :period, :class => 'form-control'
              .row
                .field
                  %tr
                    .col-sm-3
                      = f.label :date
                  %tr
                    .col-sm-3
                      = f.text_field :date, :class => 'datepicker form-control'
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
            = f.submit "save", :class => 'btn btn-primary'
          

.pull-left
  .row
    = form_tag staffs_path, :method => 'get' do
      .col-sm-12
        .col-sm-8
          = select_tag(:search,options_for_select([['PP1'],['PP2'],['1'],['2'],['3'],['4'],['5'],['6'],['7'],['8'],['9'],['10'],['11'],['12']],:selected => :grade),{:class => 'col-sm-4 form-control'})

        .col-sm-3
          = submit_tag "Search", :class => 'btn btn-primary'
%br
.row
  %center
    %h3
      Listing staffs
    %table.table.table-striped.table-condensed.table-bordered
      %tr
        %th Staff name
        %th Staff exp
        %th Grade
        %th Start time
        %th End time
        %th Period
        %th Date
        
 
        - @staffs.each do |staff|
          %tr
            %td= staff.staff_name
            %td= staff.staff_exp
            %td= staff.grade
            %td= staff.start_time
            %td= staff.end_time
            %td= staff.period
            %td= staff.date
                  
%br
    

app/views/staffs/new.html.haml
%h3 New Assessment

= render 'form'

app/views/staffs/show.html.haml
%p#notice= notice

%p
  %b Staff name:
  = @staff.staff_name
%p
  %b Staff exp:
  = @staff.staff_exp
%p
  %b Grade:
  = @staff.grade
%p
  %b Start time:
  = @staff.start_time
%p
  %b End time:
  = @staff.end_time
%p
  %b Period:
  = @staff.period
%p
  %b Date:
  = @staff.date

= link_to button_tag('Edit',:class => 'btn btn-primary'), edit_staff_path(@staff)