config/routes.rb
ManthanErp::Application.routes.draw do

  resources :messages

  get 'locations/index'

  resources :grade_lab_mappings do
    collection do
      get "get_grades_subjects_service_view"
      get "all_subjects"
      get "get_subjects_grades_service_view"
      post "save_subjects_mappings"
      get "get_grades_subjects_service_view"    
    end
  end

  resources :guest_managements do
    collection do
      get "get_role_view"
    end
  end
 

  resources :food_wastages do
    collection do
      get "get_food_wastage"
    end
  end
  

  get "teaching_plans/new"
  get "teaching_plans/edit"
  get "teaching_plans/index"
  get "teaching_plans/show"
  resources :lib_reports do
    collection do
      get 'Leastused'
      get 'popup'
      end
    end
  resources :donation_of_books do
    collection do
      get 'gradeserviceview'
      get 'sectionserviceview'
      end
    end
  
  resources :student_route_mappings do
    collection do
      get 'get_route_optimization'
      get "get_search_students"
      get "get_up_route_view"
      get "get_down_route_view"
      get "get_student_view"
      post "save_route"
    end
  end
  
  resources :interviewschedulrs do
    member do
      get 'home_index'
    end
  end
  resources :block_books do
    collection do
      get 'get_book_service_view'
      get 'getbooks'
      post 'savebooks'
      post 'damagebooks'
      
    end
  end 
 
  resources :request_new_books do
    collection do
      get 'request_new'
      get 'request_approval'
      post 'create_bulk'
      get 'request_new_book'
      get 'request_accept'
      get 'suggest_teacher'
      get 'book_accept'
      get 'book_reject'
     
    end
     member do
      get 'home_request_approval'
      get 'book_request_approval'
      get 'bookrequest'
  end
  end
  resources :issuings do
    collection do
      get "student_book_issuings"
      get 'gradeserviceview'
      get 'grade_section_service'
    end
  end
  resources :damagebooks do
    collection do
      get 'get_book_service_view'
      post 'damagebooks'
      get 'get_damage_books'
    end
  end 
  resources :staffs
  get "staffs/staffview"

  devise_for :users, :controllers => { :sessions => 'sessions'}
  
  get 'auto_search/autocomplete_location_master_location_name'
  get 'auto_search/autocomplete_student_master_name'
  get 'auto_search/autocomplete_faculty_master_faculty_name'
  get 'auto_search/student_name_by_grade_and_section'
  get 'auto_search/autocomplete_book_isbn'
  get 'auto_search/autocomplete_staff_grade'
  get 'auto_search/autocomplete_user_email'
  get 'auto_search/autocomplete_mail_search'
  get "time_tables/gradeserviceview"
  get "time_tables/sectionserviceview"
  get "/time_tables/subjectserviceview"
  post "/time_tables/saveperiods"
  get "/time_tables/timetableserviceview"
  post "/time_tables/getperiods"
  get "/time_tables/getperiods"
  get "/time_tables/defaultperiodsserviceview"
  post "/time_tables/checktimetable"
  get "/time_tables/checktimetable"

  #get "/teaching_plans/gradeserviceview"
  #get "/teaching_plans/sectionserviceview"

  resources :time_tables do
    collection do       
      get "get_sections_for_grade"
      get "get_subjects_for_grade"
    end 
  end 

  resources :books do 
    member do 
    end
    collection do       
      post 'create_bulk'
      post 'add_bulk'
    end
  end
  resources :teaching_plans do
     collection do
      get "calendardata"
      get "getfacultyidservice"
      get "getgradessectionsservice"      
      get 'calendarpopup'
      get 'monthlywiseplan'
      get 'get_grade_section_subject_service'
      get 'teaching_date'
      get 'getmonthlycalendarservice'
      get 'getmonthdataservice'
      get "student_teaching_plans"
      get 'getfacultydatesservice' 
      get 'plan_exists' 

    end
  end

  resources :documentuploaders do
    member do
      get 'home_index'
    end
  end
  
  resources :new_vehicles do
    collection do
      get 'home'
      get 'get_vendor_name'
    end
  end
  resources :forms do
    member do
      get 'home_index'
    end
  end

  resources :discounts 
  resources :approval_items do
    member do
      put "approve"
      put "reject"
    end
    collection do
      get "fee_structure_approval_item"
    end
  end
  resources :events

  resources :fee_types do
    collection do
      post "create_bulk"
    end
  end
  resources :fee_grade_buckets do
    collection do
      post "create_bulk"
      get "all_grades"
      delete "destroy_all"
    end
  end
  resources :term_definitions do
    collection do
      post "create_bulk"
      delete "destroy_all"
    end
  end
  
  resources :grade_wise_fees do
    collection do
      get "grade_wise_fee_view"
      post "save_grade_wise_fee_grid"
      get "grade_wise_fee_of_student"
    end
  end


  resources :term_wise_grade_fees do
    collection do
      get "term_wise_grade_fee"
      post "save_term_wise_fee_grid"
      get "term_wise_fee_of_student"
    end
  end

  
  resources :monthly_pdc_amounts  do
    collection do
      get "monthly_pdc_amounts"
      post "save_monthly_pdc_amounts"
      get "month_wise_fee_of_student"
    end
  end


  resources :post_dated_cheques do
    collection do
      post "create_bulk"
      delete "destroy_all"
    end
  end
  
  get "fee_alerts/fee_struct_mail_to_parents" 

  resources :student_masters do
    collection do
      get "belongs_to_parent"
      get "new_upload"
      post "upload"
    end
    member do
      get 'monthly_pdcs'
      get 'next_term_fee'
      get "annual_discount_details"
      get "dashboard"
      put "update_address"
      get "attendance_calendar_for_month"
      get "student_summarized_monthly_report"
      get "transport_details"
      put "change_transport"
    end
  end
  
  resources :parent_payment_masters do
    collection do
      get "pay"
      get "transaction_types"
      get "student_transactions"
    end
    member do
      get "pending_pdcs"
      get "cleared_pdcs"
      get "payment_transactions"
      get "submitted_pdcs"
      get "print"
    end
  end
  resources :parent_payment_transactions do
    member do
      get "print"
      get "in_detail"
    end
  end
  

 
  
  resources :staffs do
    member do
      get 'event_new'
    end
    collection do
      get 'event_index'
      get 'staffs/staffview'
    end
  end

  resources :parent_cheques

  resources :job_runs do
    member do
      get "failure_recipients"
    end
  end
  
  resources :default_masters do 
    collection do
      get "day_ends"
      put "days"
    end
  end
  
  resources :academics do
    collection do
      get "get_grades"
      get "get_academics_subjects"
      get "get_sections_for_grade"
      get "get_academics_subjects_for_grade"
    end
  end


  resources :teachers_time_tables do
    collection do
      get "get_faculty_names_view"
      get "get_faculty_garde_sections_view"
      get "check_teachers_timetable"
      post "saveperiods"
      post "getperiods"
    end  
  end

  resources :teacher_grade_mappings do
    collection do
      get "check_teachers_grades_mapping"
      post "savemappings"
      post "getmappings" 
      post "deletemappings"  
      get "show_grade_wise"
      get "get_grade_wise_mappings"   
      end
  end
  
  get "/parent_payment_transactions/parent_transactions"
  get "/parent_payment_transactions/admin_transactions"

  resources :grade_masters do
    member do
      get "sections"
    end
    resources :section_masters
  end

  resources :parent_masters do
    collection do
      get "new_upload"
      post "upload"
    end
  end

  resources :class_teacher_mappings do
    collection do
      get "get_grade_wise_mappings"
      get "get_grade_wise_faculty_names"  
      get "get_class_teacher_mappings" 
      post "save_mappings"
      post "deletemappings"
      get "check_for_teacher_mapping"
    end  
  end

  resources :grades_sections_mappings do
    collection do
      get "get_grades_sections_service_view"
      post "save_sections_mappings" 
      post "save_grades_mappings"         
    end  
  end

  resources :grades_subjects_mappings do
    collection do
      get "get_grades_subjects_service_view"
      post "save_subjects_mappings" 
      post "save_grades_mappings"    
    end  
  end 

  resources :gradings do
    collection do
    get "get_grading_service_view"
    post "save_gradings_mappings"
    post "delete_grading_mappings"
    end
  end
  
  resources :location_masters

  
  resources :recruitments do
    member do
      
      put 'update_admission'
      get "homeindex"
      get "view_document"
      get 'create_enquiry'
      get "document_verification"
      get 'view_assessment'
      get 'assessment_result'
      put 'update_rec'
      put 'update_ass'
      put 'update_man'
      put 'update_close'
      get 'assessment_new'
    end
    collection do
      
      get 'recruitment_home'
      get 'get_subject_view'
      get 'get_klass_view'
      get 'enquiry_new'
      post 'create_enquiry'
      get 'document_index'
      get 'sports_index'
      get 'assessment_index'
      get 'assessment_completed_index'
      get 'management_index'
      get 'selected_staffs'
      get 'closed_forms'
    end
  end
  resources :staff_admissions do
    member do
      get 'homeindex'
      get "document_verification"
      post 'update_close'
      put 'update_admission'
      put 'update_man'
    end
    collection do
      get 'get_head_view'
      get 'get_post_view'
      get 'get_subject_view'
      get 'get_klass_view'
      get 'enquiry_index'
     
    end
  end
  
  resources :teacher_leaders
  
  resources :adds do 
    collection do
      get 'get_dept_view'
    end
  end
 
  resources :assessment_criterias do
    collection do
      get "get_assessment_criteria_service"       
      post "save_assessment_criterias"
      post "deletemappings"
      get "get_grade_subject_service"
      get "get_assessment_criteria"
    end
  end

app/models/vendor_management.rb
class VendorManagement < ActiveRecord::Base
  belongs_to :vendor_category
  # validates :vendor_name , :presence => true
  # validates_format_of :vendor_email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  # validates :vendor_address, :presence => true
  # validates :verdor_mobile, :presence => true
  # validates :contact_name, :presence => true
  
end

app/controllers/vendor_managements_controller.rb
class VendorManagementsController < ApplicationController
  def index
    @vendor_managements =  VendorManagement.all
  end

  def new
  end

  def edit
    @vendor_management = VendorManagement.find(params[:id])
  end

  def get_vendor_view
    vendor = VendorCategory.all.map do |vendor|
      { vendor: vendor.vendor_category ,id: vendor.id}
    end
    render :json => vendor
  end
  
  
  def show
  end
  def create 
    @vendor_management = VendorManagement.new(vendor_params)
    if @vendor_management.save
      redirect_to  vendor_managements_path
    else
      render "new"
    end
  end

  def destroy
    @vendor_management = VendorManagement.find(params[:id])
    if @vendor_management.destroy
      flash[:success] = I18n.t :success, :scope => [:vendor_management ,:destroy]
    else
      flash.now[:fail] = I18n.t :fail, :scope => [:vendor_management, :destroy]
    end
    redirect_to vendor_managements_path
  end

   def update
    @vendor_management = VendorManagement.find(params[:id])
    if @vendor_management.update(vendor_params)
      flash[:success] = I18n.t :success, :scope => [:vendor_management, :update]
      redirect_to vendor_managements_path
    else
      flash.now[:fail] = I18n.t :fail, :scope => [:vendor_management, :update]
      render "edit"
    end
  end

  def vendor_params
    params.require(:vendor_management).permit(:vendor_category_id,:contact_name, :vendor_name,:vendor_phone, :vendor_address, :vendor_alternate_email, :vendor_email , :verdor_mobile)
  end

end

app/helpers/vendor_managements_helper.rb
module VendorManagementsHelper
end

app/views/vendor_managements/day_ends.html.haml
.row{:ng_controller => "DesignationMasterController" , :ng_init => "getDayEnd()" }
  .col-sm-6
    .pull-right
      = link_to raw("<i class='fa fa-save fa-lg'></i> Edit"), "#", :class => "btn btn-primary", :ng_click => "editable = true", :ng_hide => "editable" 
    %br
    %br
    %h4
      %table
        %thead
          %th Day ends
        %tbody
          %tr{:ng_repeat => "day_end in day_ends"}
            %td
              %br
              .form-group
                %label{:ng_hide => "editable" , :class => "form-control"} {{day_end.transaction_date}}
                %div{:ng_show => "editable"}
                  %input{:ng_model => "day_end.transaction_date" , :class => "form-control" , :my_datepicker => true } 
                  %br
                  .pull-right
                    = link_to raw("<i class='fa fa-save fa-lg'></i> Update"), "#", :class => "btn btn-primary",:ng_click => "saveDayEnds(day_end)" , :ng_show => "editable"
              
            

app/views/vendor_managements/edit.html.haml
.row
  .col-sm-10
    %h4 New Vendor
= form_for @vendor_management , :html => { :class => "form-horizontal", :role => "form"} do |f| 
  = render "shared/error_messages", :object => f.object
  .row{"ng-controller" => "VendorController"}
    .col-sm-2
      = f.label "Category"
    .col-sm-4
      %select{"ng-model" => "vendor", "ng-options" => " vendor.vendor for vendor in vendors",:class => "form-control",:required => "required", :value => params[:category]}
        %option{value: ""} Select Vendor
        = f.hidden_field :vendor_categories_id, :value => "{{vendor.id}}"
      %br
  .row
    .col-sm-2
      = f.label "Vendor Name"
    .col-sm-4
      = f.text_field "vendor_name", :class => 'form-control'
      %br
    .col-sm-2
      = f.label "Contact Name"
    .col-sm-4
      = f.text_field "contact_name", :class => 'form-control'
  .row
    .col-sm-2
      = f.label "Vendor Phone"
    .col-sm-4
      = f.text_field "vendor_phone", :class => 'form-control'
      %br
    .col-sm-2
      = f.label "Mobile#"
    .col-sm-4
      = f.text_field "verdor_mobile", :class => 'form-control'
  .row
    .col-sm-2
      = f.label "Vendor Email"
    .col-sm-4
      = f.text_field "vendor_email", :class => 'form-control'
      %br
    .col-sm-2
      = f.label "Alternate Email"
    .col-sm-4
      = f.text_field "vendor_alternate_email", :class => 'form-control'
  .row
    .col-sm-2
      = f.label "Address"
    .col-sm-4
      = f.text_area "vendor_address", :class => 'form-control'
      %br
  .row
    .col-sm-10
    .col-sm-2
      = button_tag "Save", :type => "submit", :class => 'btn btn-primary'

app/views/vendor_managements/index.html.haml
.row
  .col-sm-10
    %h3  Vendor 
  .col-sm-2
    = link_to "Add New",  new_vendor_management_path, :class => "btn btn-primary"
    %br
.row
  .col-sm-11
    %table.table.table-bordered
      %thead
        %tr
          %th Category
          %th Name
          %th Phone#
          %th Mobile#
          %th Email
          %th 
      %tbody
        - @vendor_managements.each do |vendor|        
          %tr
            %td= vendor.vendor_category.vendor_category
            %td= vendor.vendor_name
            %td= vendor.vendor_phone
            %td= vendor.verdor_mobile
            %td= vendor.vendor_email
            %td
              = link_to raw("<span class='glyphicon glyphicon-trash'></span>"), vendor_management_path(vendor), :class => "form btn-sm btn-danger ",:data => {:method => 'delete' ,:confirm => "Are You Sure to Delete " }
              = link_to raw("<span class='glyphicon glyphicon-edit'></span>"), edit_vendor_management_path(vendor, :category => vendor.vendor_category.vendor_category), :class => "form btn-sm btn-warning "



       
              

app/views/vendor_managements/new.html.haml
.row
  .col-sm-10
    %h4 New Vendor
= form_for VendorManagement.new , :html => { :class => "form-horizontal", :role => "form"} do |f| 
  = render "shared/error_messages", :object => f.object
  .row{"ng-controller" => "VendorController"}
    .col-sm-2
      = f.label "Category"
    .col-sm-4
      %select{"ng-model" => "vendor", "ng-options" => " vendor.vendor for vendor in vendors",:class => "form-control",:required => "required", }
        %option{style: "display:none", value: ""} Select Vendor
        = f.hidden_field :vendor_category_id, :value => "{{vendor.id}}"
       
      %br
  .row
    .col-sm-2
      = f.label "Vendor Name"
    .col-sm-4
      = f.text_field "vendor_name", :class => 'form-control'
      %br
    .col-sm-2
      = f.label "Contact Name"
    .col-sm-4
      = f.text_field "contact_name", :class => 'form-control'
  .row
    .col-sm-2
      = f.label "Vendor Phone"
    .col-sm-4
      = f.text_field "vendor_phone", :class => 'form-control'
      %br
    .col-sm-2
      = f.label "Mobile#"
    .col-sm-4
      = f.text_field "verdor_mobile", :class => 'form-control'
  .row
    .col-sm-2
      = f.label "Vendor Email"
    .col-sm-4
      = f.text_field "vendor_email", :class => 'form-control'
      %br
    .col-sm-2
      = f.label "Alternate Email"
    .col-sm-4
      = f.text_field "vendor_alternate_email", :class => 'form-control'
  .row
    .col-sm-2
      = f.label "Address"
    .col-sm-4
      = f.text_area "vendor_address", :class => 'form-control'
      %br
  .row
    .col-sm-10
    .col-sm-2
      = button_tag "Save", :type => "submit", :class => 'btn btn-primary'