config/routes.rb
ManthanErp::Application.routes.draw do

  resources :messages

  get 'locations/index'

  resources :grade_lab_mappings do
    collection do
      get "get_grades_subjects_service_view"
      get "all_subjects"
      get "get_subjects_grades_service_view"
      post "save_subjects_mappings"
      get "get_grades_subjects_service_view"    
    end
  end

  resources :guest_managements do
    collection do
      get "get_role_view"
    end
  end
 

  resources :food_wastages do
    collection do
      get "get_food_wastage"
    end
  end
  

  get "teaching_plans/new"
  get "teaching_plans/edit"
  get "teaching_plans/index"
  get "teaching_plans/show"
  resources :lib_reports do
    collection do
      get 'Leastused'
      get 'popup'
      end
    end
  resources :donation_of_books do
    collection do
      get 'gradeserviceview'
      get 'sectionserviceview'
      end
    end
  
  resources :student_route_mappings do
    collection do
      get 'get_route_optimization'
      get "get_search_students"
      get "get_up_route_view"
      get "get_down_route_view"
      get "get_student_view"
      post "save_route"
    end
  end
  
  resources :interviewschedulrs do
    member do
      get 'home_index'
    end
  end
  resources :block_books do
    collection do
      get 'get_book_service_view'
      get 'getbooks'
      post 'savebooks'
      post 'damagebooks'
      
    end
  end 
 
  resources :request_new_books do
    collection do
      get 'request_new'
      get 'request_approval'
      post 'create_bulk'
      get 'request_new_book'
      get 'request_accept'
      get 'suggest_teacher'
      get 'book_accept'
      get 'book_reject'
     
    end
     member do
      get 'home_request_approval'
      get 'book_request_approval'
      get 'bookrequest'
  end
  end
  resources :issuings do
    collection do
      get "student_book_issuings"
      get 'gradeserviceview'
      get 'grade_section_service'
    end
  end
  resources :damagebooks do
    collection do
      get 'get_book_service_view'
      post 'damagebooks'
      get 'get_damage_books'
    end
  end 
  resources :staffs
  get "staffs/staffview"

  devise_for :users, :controllers => { :sessions => 'sessions'}
  
  get 'auto_search/autocomplete_location_master_location_name'
  get 'auto_search/autocomplete_student_master_name'
  get 'auto_search/autocomplete_faculty_master_faculty_name'
  get 'auto_search/student_name_by_grade_and_section'
  get 'auto_search/autocomplete_book_isbn'
  get 'auto_search/autocomplete_staff_grade'
  get 'auto_search/autocomplete_user_email'
  get 'auto_search/autocomplete_mail_search'
  get "time_tables/gradeserviceview"
  get "time_tables/sectionserviceview"
  get "/time_tables/subjectserviceview"
  post "/time_tables/saveperiods"
  get "/time_tables/timetableserviceview"
  post "/time_tables/getperiods"
  get "/time_tables/getperiods"
  get "/time_tables/defaultperiodsserviceview"
  post "/time_tables/checktimetable"
  get "/time_tables/checktimetable"

  #get "/teaching_plans/gradeserviceview"
  #get "/teaching_plans/sectionserviceview"

  resources :time_tables do
    collection do       
      get "get_sections_for_grade"
      get "get_subjects_for_grade"
    end 
  end 

  resources :books do 
    member do 
    end
    collection do       
      post 'create_bulk'
      post 'add_bulk'
    end
  end
  resources :teaching_plans do
     collection do
      get "calendardata"
      get "getfacultyidservice"
      get "getgradessectionsservice"      
      get 'calendarpopup'
      get 'monthlywiseplan'
      get 'get_grade_section_subject_service'
      get 'teaching_date'
      get 'getmonthlycalendarservice'
      get 'getmonthdataservice'
      get "student_teaching_plans"
      get 'getfacultydatesservice' 
      get 'plan_exists' 

    end
  end

  resources :documentuploaders do
    member do
      get 'home_index'
    end
  end
  
  resources :new_vehicles do
    collection do
      get 'home'
      get 'get_vendor_name'
    end
  end
  resources :forms do
    member do
      get 'home_index'
    end
  end

  resources :discounts 
  resources :approval_items do
    member do
      put "approve"
      put "reject"
    end
    collection do
      get "fee_structure_approval_item"
    end
  end
  resources :events

  resources :fee_types do
    collection do
      post "create_bulk"
    end
  end
  resources :fee_grade_buckets do
    collection do
      post "create_bulk"
      get "all_grades"
      delete "destroy_all"
    end
  end
  resources :term_definitions do
    collection do
      post "create_bulk"
      delete "destroy_all"
    end
  end
  
  resources :grade_wise_fees do
    collection do
      get "grade_wise_fee_view"
      post "save_grade_wise_fee_grid"
      get "grade_wise_fee_of_student"
    end
  end


  resources :term_wise_grade_fees do
    collection do
      get "term_wise_grade_fee"
      post "save_term_wise_fee_grid"
      get "term_wise_fee_of_student"
    end
  end

  
  resources :monthly_pdc_amounts  do
    collection do
      get "monthly_pdc_amounts"
      post "save_monthly_pdc_amounts"
      get "month_wise_fee_of_student"
    end
  end


  resources :post_dated_cheques do
    collection do
      post "create_bulk"
      delete "destroy_all"
    end
  end
  
  get "fee_alerts/fee_struct_mail_to_parents" 

  resources :student_masters do
    collection do
      get "belongs_to_parent"
      get "new_upload"
      post "upload"
    end
    member do
      get 'monthly_pdcs'
      get 'next_term_fee'
      get "annual_discount_details"
      get "dashboard"
      put "update_address"
      get "attendance_calendar_for_month"
      get "student_summarized_monthly_report"
      get "transport_details"
      put "change_transport"
    end
  end
  
  resources :parent_payment_masters do
    collection do
      get "pay"
      get "transaction_types"
      get "student_transactions"
    end
    member do
      get "pending_pdcs"
      get "cleared_pdcs"
      get "payment_transactions"
      get "submitted_pdcs"
      get "print"
    end
  end
  resources :parent_payment_transactions do
    member do
      get "print"
      get "in_detail"
    end
  end
  

 
  
  resources :staffs do
    member do
      get 'event_new'
    end
    collection do
      get 'event_index'
      get 'staffs/staffview'
    end
  end

  resources :parent_cheques

  resources :job_runs do
    member do
      get "failure_recipients"
    end
  end
  
  resources :default_masters do 
    collection do
      get "day_ends"
      put "days"
    end
  end
  
  resources :academics do
    collection do
      get "get_grades"
      get "get_academics_subjects"
      get "get_sections_for_grade"
      get "get_academics_subjects_for_grade"
    end
  end


  resources :teachers_time_tables do
    collection do
      get "get_faculty_names_view"
      get "get_faculty_garde_sections_view"
      get "check_teachers_timetable"
      post "saveperiods"
      post "getperiods"
    end  
  end

  resources :teacher_grade_mappings do
    collection do
      get "check_teachers_grades_mapping"
      post "savemappings"
      post "getmappings" 
      post "deletemappings"  
      get "show_grade_wise"
      get "get_grade_wise_mappings"   
      end
  end
  
  get "/parent_payment_transactions/parent_transactions"
  get "/parent_payment_transactions/admin_transactions"

  resources :grade_masters do
    member do
      get "sections"
    end
    resources :section_masters
  end

  resources :parent_masters do
    collection do
      get "new_upload"
      post "upload"
    end
  end

  resources :class_teacher_mappings do
    collection do
      get "get_grade_wise_mappings"
      get "get_grade_wise_faculty_names"  
      get "get_class_teacher_mappings" 
      post "save_mappings"
      post "deletemappings"
      get "check_for_teacher_mapping"
    end  
  end

  resources :grades_sections_mappings do
    collection do
      get "get_grades_sections_service_view"
      post "save_sections_mappings" 
      post "save_grades_mappings"         
    end  
  end

  resources :grades_subjects_mappings do
    collection do
      get "get_grades_subjects_service_view"
      post "save_subjects_mappings" 
      post "save_grades_mappings"    
    end  
  end 

  resources :gradings do
    collection do
    get "get_grading_service_view"
    post "save_gradings_mappings"
    post "delete_grading_mappings"
    end
  end
  
  resources :location_masters

  
  resources :recruitments do
    member do
      
      put 'update_admission'
      get "homeindex"
      get "view_document"
      get 'create_enquiry'
      get "document_verification"
      get 'view_assessment'
      get 'assessment_result'
      put 'update_rec'
      put 'update_ass'
      put 'update_man'
      put 'update_close'
      get 'assessment_new'
    end
    collection do
      
      get 'recruitment_home'
      get 'get_subject_view'
      get 'get_klass_view'
      get 'enquiry_new'
      post 'create_enquiry'
      get 'document_index'
      get 'sports_index'
      get 'assessment_index'
      get 'assessment_completed_index'
      get 'management_index'
      get 'selected_staffs'
      get 'closed_forms'
    end
  end
  resources :staff_admissions do
    member do
      get 'homeindex'
      get "document_verification"
      post 'update_close'
      put 'update_admission'
      put 'update_man'
    end
    collection do
      get 'get_head_view'
      get 'get_post_view'
      get 'get_subject_view'
      get 'get_klass_view'
      get 'enquiry_index'
     
    end
  end
  
  resources :teacher_leaders
  
  resources :adds do 
    collection do
      get 'get_dept_view'
    end
  end
 
  resources :assessment_criterias do
    collection do
      get "get_assessment_criteria_service"       
      post "save_assessment_criterias"
      post "deletemappings"
      get "get_grade_subject_service"
      get "get_assessment_criteria"
    end
  end

app/controllers/parent_payment_masters_controller.rb
class ParentPaymentMastersController < ApplicationController
  load_resource :only => [:new, :pending_pdcs, :cleared_pdcs, :update, :payment_transactions, :submitted_pdcs, :print]

  def index
    if current_user.parent?
      @students = current_user.parent.students
      @students = StudentMastersDecorator.decorate_collection(@students)
      render "shared/student_payment_index"
    else
      render "index"
    end
  end
  
  def new
    if params[:student_id].present?
      @parent_payment_master.student_id = params[:student_id]
    end
  end
 
  def create
    respond_to do |format|
      format.json do
        unless current_user.parent?
          @parent_payment_master = ParentPaymentMaster.new(parent_payment_master_params)
          @parent_payment_master.parent = @parent_payment_master.student.parent
          payment_creation_service = PaymentCreationService.new(@parent_payment_master, params[:parent_payment_master], DateTime.now)
          if payment_creation_service.save
            render :json => {status: true, :parent_payment_master_id => payment_creation_service.parent_payment_master.id, :last_transaction_id => payment_creation_service.last_transaction.id} #"acknowledgement"
          else
            render :json => {status: false, errors: payment_creation_service.errors}
          end
        else
          render "payment_gateway"
        end
      end
    end
  end

  def update
    respond_to do |format|
      format.json do
        unless current_user.parent?
          payment_creation_service = PaymentCreationService.new(@parent_payment_master, params[:parent_payment_master], DateTime.now)
          if payment_creation_service.save
            render :json => {status: true, :parent_payment_master_id => payment_creation_service.parent_payment_master.id, :last_transaction_id => payment_creation_service.last_transaction.id} #"acknowledgement"
            
          else
            render :json => {status: false, errors: payment_creation_service.errors}
          end
        else
          render "payment_gateway"
        end
      end
    end
  end

  def pay
    @student_master = StudentMaster.where(:id => params[:student_id]).first if params[:student_id].present? 
    if @student_master.present?
      if ApprovalItem.fee_structure_approved?
        @parent_payment_master = ParentPaymentMaster.find_by_student_id(@student_master.id)
        if @parent_payment_master.present?
          render "edit"
        else
          @parent_payment_master = ParentPaymentMaster.new_student_payment_master(@student_master.id)
          render "new"
        end
      else
        flash[:fail] = I18n.t :pending, :scope => [:approval_items, :fee_structure]
        redirect_to parent_payment_masters_path
      end
    else
      flash[:fail] = I18n.t :not_found, :scope => [:student_master, :search]
      redirect_to parent_payment_masters_path
    end
  end
  
  def pending_pdcs
    respond_to do |format|
      format.json do
        submitted_pdcs = @parent_payment_master.parent_payment_transactions.cheque_type_transactions.pending_transactions.map do |pt|
          Struct.new(:month, :cheque_number, :cheque_date, :amount_in_rupees).new(pt.parent_cheque.post_dated_cheque.month, pt.parent_cheque.cheque_number, pt.parent_cheque.cheque_date, pt.amount_in_rupees)
        end
        render :json => submitted_pdcs
      end
    end
  end

  def cleared_pdcs
    respond_to do |format|
      format.json do
        cleared_pdcs = @parent_payment_master.parent_payment_transactions.cheque_type_transactions.cleared_transactions.map do |ppt|
          Struct.new(:month, :cheque_number, :cleared_date, :amount_in_rupees).new(ppt.parent_cheque.post_dated_cheque.month, ppt.parent_cheque.cheque_number, ppt.transaction_date, ppt.amount_in_rupees)
        end
        render :json => cleared_pdcs
      end
    end
  end

  def submitted_pdcs
    respond_to do |format|
      format.json do
        submitted_pdcs = @parent_payment_master.parent_payment_transactions.cheque_type_transactions.map do |pt|
          Struct.new(:cheque_number, :cheque_date, :amount_in_rupees, :bank_name, :ifsc_code, :status).new(pt.parent_cheque.cheque_number, pt.parent_cheque.cheque_date, pt.amount_in_rupees, pt.parent_cheque.bank_name, pt.parent_cheque.ifsc_code, pt.parent_cheque.status)
        end
        render :json => submitted_pdcs
      end
    end
  end
  
  def payment_transactions
    respond_to do |format|
      format.json do
        render :json => @parent_payment_master.parent_payment_transactions
      end
    end
  end

  def transaction_types
    if current_user.parent?
      @transaction_types = [{value: "online", text: "Online"}]
    else
      @transaction_types = [{value: "cash", text: "CASH"}, {value: "cheque", text: "CHEQUE"}]
    end
    respond_to do |format|
      format.json do
        render :json => @transaction_types
      end
    end
  end

  def student_transactions
    @parent_payment_master = ParentPaymentMaster.find_by_student_id(params[:student_id])
    respond_to do |format|
      format.json do
        data = @parent_payment_master.present? ? @parent_payment_master.parent_payment_transactions.map{|transaction| transaction.attributes} : []
        render :json => data
      end
    end
  end
  
  def print
    respond_to do |format|
      format.pdf do
        @payment_receipt = PaymentReceipt.new(:branch_abbr => "T", :receipt_date => DateTime.now)
        if @payment_receipt.save!
          render :pdf => "Reciept ",
          :template => 'parent_payment_masters/print_monthly_payment_pdcs',
          :formats => [:pdf, :haml],
          :orientation => 'Landscape',
          :page_size  => 'A4',
          :margin => {:top => '8mm',
            :bottom => '8mm',
            :left => '14mm',
            :right => '14mm'}
        end
      end
    end
  end
  

  private
  def parent_payment_master_params
    params.require(:parent_payment_master).permit(:payment_type_id, :student_id)
  end
  
end

app/helpers/parent_payment_masters_helper.rb
module ParentPaymentMastersHelper
end

app/views/parent_payment_masters/_cleared_pdcs.html.haml
.col-md-12
  .panel.panel-default
    .panel-heading
      Cleared PDCs
    %table.table.table-bordered.table-striped.table-hover
      %thead
        %th Month
        %th Amount
        %th Cheque Number
        %th Cleared Date
      %tbody
        %tr{"ng-repeat" => "pdc in monthly_pdcs"}
          %td {{pdc.month}}
          %td {{pdc.amount_in_rupees}}
          %td {{pdc.cheque_number}}
          %td {{pdc.cleared_date}}

app/views/parent_payment_masters/_edit_form.html.haml
%form{:class => "form-horizontal", :role => "form"}
  .row{:ng_show => "errors"}
    .alert.alert-danger{:ng_repeat => "(key, value) in errors"} {{value.join(",")}}
  - if @parent_payment_master.term_wise_payment? 
    .col-md-12{:ng_init => "routeToTermFee()"}
      %div{"ng-view" => true }

app/views/parent_payment_masters/_form.html.haml
%form{:class => "form-horizontal", :role => "form", :ng_submit => "doPayment()", :action => "#"}
  .row{:ng_show => "errors"}
    .alert.alert-danger{:ng_repeat => "(key, value) in errors"} {{key}} : {{value.join(",")}}
  - PaymentType.all.order("code").each do |type|
    .form-group.col-md-3
      = radio_button_tag :payment_type_id, type.id, "", :class => "col-md-2", :ng_click => "go('#{type.code}', '#{@parent_payment_master.student_id}')", :ng_disabled => "#{current_user.parent? and type.code == 'monthly'}", :ng_model => "payment_type_id", :ng_disabled => "submitted"
      %label.font-mid-17= "#{type.code.titleize}"

  = hidden_field_tag :student_id, "",:ng_model => "student_id"
  .col-md-9
    %div{"ng-view" => true }

app/views/parent_payment_masters/_monthly_pdc_history.html.haml
%h4.panel-title 
  = "Post Dated Cheques"
  = link_to (fa_icon "angle-double-up lg", :id => "collapse-icon"),"#" ,:class => "collapse-link pull-right", :data => {:toggle => "collapse", :target => "#collapse-div0"}
%hr
  #collapse-div0
    .col-md-6{:ng_controller => "MonthlyPdcsController", :ng_init => "pending_pdcs('#{@parent_payment_master.id}')"}
      = render "pending_pdcs"
    .col-md-6{:ng_controller => "MonthlyPdcsController", :ng_init => "cleared_pdcs('#{@parent_payment_master.id}')"}
      = render "cleared_pdcs"

app/views/parent_payment_masters/_pending_pdcs.html.haml
.col-md-12
  .panel.panel-default
    .panel-heading
      Pending PDCs
    %table.table.table-bordered.table-striped.table-hover
      %thead
        %th Month
        %th Amount
        %th Cheque Number
      %tbody
        %tr{"ng-repeat" => "pdc in monthly_pdcs"}
          %td {{pdc.month}}
          %td {{pdc.amount_in_rupees}}
          %td {{pdc.cheque_number}}

app/views/parent_payment_masters/_print_pdc_content.pdf.haml
= render "shared/brand_header", :handlers => [:pdf, :haml]        
.col-md-4
  %table.table
    %tr
      %th Date:
      %td= Date.today.strftime("%d-%m-%Y")
%label Cheques Recieved
%table.table.table-bordered
  %thead
    %th Date
    %th Amount
    %th Cheque #
    %th Bank
    %th IFSC
  %tbody
    - @parent_payment_master.parent_payment_transactions.each do |transaction|
      %tr
        %td= transaction.parent_cheque.post_dated_cheque.date
        %td= transaction.amount_in_rupees
        %td= transaction.parent_cheque.cheque_number
        %td= transaction.parent_cheque.bank_name
        %td= transaction.parent_cheque.ifsc_code
        
      

app/views/parent_payment_masters/_search.html.haml
.colmd-10{:ng_controller => "GradeSectionsController"}
  = form_tag pay_parent_payment_masters_path, :method => 'get' , :class => "form-inline", :name => "StudentSearchForm" do
    .form-group.col-md-3
      %label{:class=> "form-label col-md-4"} Grade
      .col-md-6
        %select{:ng_model => "grade", :ng_options => "gr.grade_name for gr in grades", :class=>"form-control", :ng_change => "fetchSections()"}
    .form-group.col-md-3
      %label{:class=> "form-label col-md-4"} Section
      .col-md-6
        %select{:ng_model => "section", :ng_options => "sc.section_name for sc in sections", :class=>"form-control"}
    .form-group.col-md-5
      .col-md-3
        %label{:class=> "form-label col-md-4"} Student
      .col-md-6
        = autocomplete_field_tag :student,
        '',
        "/auto_search/student_name_by_grade_and_section?grade={{grade.id}}&section= {{section.id}}",
        :placeholder => "Student Name", :class => 'form-control',
          :required => true,
          :id_element => "#student_id"
      .col-md-3
        = hidden_field_tag :student_id, :id => "student_id"
        = submit_tag "Go", :name => nil, :class => "btn-primary btn"

app/views/parent_payment_masters/_submitted_pdc.html.haml
.col-md-12
  .panel.panel-default
    .panel-heading
      Submitted PDCs
    %table.table.table-bordered.table-striped.table-hover
      %thead
        %th Cheque #
        %th Date
        %th Bank
        %th IFSC
        %th Amount
        %th Status
      %tbody
        %tr{"ng-repeat" => "pdc in submitted_pdcs"}
          %td {{pdc.cheque_number}}
          %td {{pdc.cheque_date}}
          %td {{pdc.bank_name}}
          %td {{pdc.ifsc_code}}
          %td {{pdc.amount_in_rupees}}
          %td 
            %span.label{:ng_class => "{true: 'label-danger', false: 'label-success'}[cheque.status === 'Pending']"}
              {{pdc.status}}

app/views/parent_payment_masters/acknowledgement.html.haml
.col-md-12
  %h4.panel-title 
    = "Payment Details"
  %hr
  .col-md-12
    %table.table.table-bordered.table-striped.table-hover
      %thead
        %th S.No
        %th Particulars
        %th Amount
      %tbody
        - @parent_payment_transaction.fee_type_contribution_amounts.each_with_index do |fee_amount, index|
          %tr
            %td= index+1
            %td= fee_amount[:fee_type]
            %td= fee_amount[:amount]
        %tr
          %th
          %th Total
          %th= @parent_payment_transaction.amount_in_rupees 
  .col-md-8
    .col-md-6
      .col-md-6
        %label Pay Mode
      .col-md-6
        = @parent_payment_transaction.transaction_type
    .col-md-6
      .col-md-6
        %label Bank
      .col-md-6
        = @parent_payment_transaction.bank_name
  .col-md-8
    .col-md-6
      .col-md-6
        %label Ref No
      .col-md-6
        = @parent_payment_transaction.ref_no
    .col-md-6
      .col-md-6
        %label Fee Mode
      .col-md-6
        = @parent_payment_master.payment_code
  .col-md-12
    .col-md-offset-4
      = link_to "Print", print_parent_payment_master_parent_payment_transaction_path(@parent_payment_master, @parent_payment_transaction, :format => :pdf), :target => "_blank", :class => "btn btn-primary"
      = link_to "Home", parent_payment_masters_path, :class => "btn btn-success"

app/views/parent_payment_masters/edit.html.haml
.col-md-12
  %student_header_details{ :student_id => "#{@parent_payment_master.student_id}"}

.col-md-12
  - if @parent_payment_master.monthly_payment? 
    = render "monthly_pdc_history"
  - else
    = render "transactions_history"
    
- unless @parent_payment_master.annual_payment? or @parent_payment_master.monthly_payment?    
  .col-md-12{:ng_controller => "PaymentsController", :ng_init => "student_id = '#{@parent_payment_master.student_id}'; parent_payment_master_id = '#{@parent_payment_master.id}'"}
    %h4.panel-title 
      = "Fee Payment"
    %hr
      = render "edit_form"

app/views/parent_payment_masters/index.html.haml
.col-md-10
  = render :partial => "shared/search_student", :locals => { :submit_path => pay_parent_payment_masters_path}

app/views/parent_payment_masters/new.html.haml
.col-md-12
  %student_header_details{ :student_id => "#{@parent_payment_master.student_id}"}

.col-md-12
  %h4.panel-title 
    = "Fee Details"
    = link_to (fa_icon "angle-double-up lg", :id => "collapse-icon"),"#" ,:class => "collapse-link pull-right", :data => {:toggle => "collapse", :target => "#collapse-div0"}
  %hr
  #collapse-div0.col-md-12.collapse
    .col-md-5
      %grade_fee_details{ :student_id => "#{@parent_payment_master.student_id}"}
    .col-md-7
      %payment_type_tabs{ :student_id => "#{@parent_payment_master.student_id}", :paymentMasterId => "#{@parent_payment_master.id}"}
  
.col-md-12{:ng_controller => "PaymentsController"}
  %h4.panel-title 
    = "Fee Payment"
  %hr
    = render "form"

app/views/parent_payment_masters/print_monthly_payment_pdcs.pdf.haml
= wicked_pdf_stylesheet_link_tag 'bootstrap'
.row
  .col-xs-6
    = render :partial => "parent_payment_masters/print_pdc_content", :handlers => [:pdf, :haml]
  .col-xs-6
    = render :partial => "parent_payment_masters/print_pdc_content", :handlers => [:pdf, :haml]

app/views/parent_payment_masters/print_transaction.pdf.haml
= wicked_pdf_stylesheet_link_tag 'bootstrap'

.row
  .col-xs-6
    = render :partial => "parent_payment_masters/print_transaction_content", :handlers => [:pdf, :haml]
  .col-xs-6
    = render :partial => "parent_payment_masters/print_transaction_content", :handlers => [:pdf, :haml]